/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as GaleriRouteImport } from './routes/galeri'
import { Route as PrasastiRouteImport } from './routes/prasasti'
import { Route as TentangRouteImport } from './routes/tentang'
import { Route as EnsiklopediaIndexRouteImport } from './routes/ensiklopedia/index'
import { Route as EnsiklopediaSlugRouteImport } from './routes/ensiklopedia/$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const GaleriRoute = GaleriRouteImport.update({
  id: '/galeri',
  path: '/galeri',
  getParentRoute: () => rootRouteImport,
} as any)
const PrasastiRoute = PrasastiRouteImport.update({
  id: '/prasasti',
  path: '/prasasti',
  getParentRoute: () => rootRouteImport,
} as any)
const TentangRoute = TentangRouteImport.update({
  id: '/tentang',
  path: '/tentang',
  getParentRoute: () => rootRouteImport,
} as any)
const EnsiklopediaIndexRoute = EnsiklopediaIndexRouteImport.update({
  id: '/ensiklopedia/',
  path: '/ensiklopedia/',
  getParentRoute: () => rootRouteImport,
} as any)
const EnsiklopediaSlugRoute = EnsiklopediaSlugRouteImport.update({
  id: '/ensiklopedia/$slug',
  path: '/ensiklopedia/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/galeri': typeof GaleriRoute
  '/prasasti': typeof PrasastiRoute
  '/tentang': typeof TentangRoute
  '/ensiklopedia/$slug': typeof EnsiklopediaSlugRoute
  '/ensiklopedia/': typeof EnsiklopediaIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/galeri': typeof GaleriRoute
  '/prasasti': typeof PrasastiRoute
  '/tentang': typeof TentangRoute
  '/ensiklopedia/$slug': typeof EnsiklopediaSlugRoute
  '/ensiklopedia': typeof EnsiklopediaIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/galeri': typeof GaleriRoute
  '/prasasti': typeof PrasastiRoute
  '/tentang': typeof TentangRoute
  '/ensiklopedia/$slug': typeof EnsiklopediaSlugRoute
  '/ensiklopedia/': typeof EnsiklopediaIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/galeri'
    | '/prasasti'
    | '/tentang'
    | '/ensiklopedia/$slug'
    | '/ensiklopedia/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/galeri'
    | '/prasasti'
    | '/tentang'
    | '/ensiklopedia/$slug'
    | '/ensiklopedia'
  id:
    | '__root__'
    | '/'
    | '/galeri'
    | '/prasasti'
    | '/tentang'
    | '/ensiklopedia/$slug'
    | '/ensiklopedia/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  GaleriRoute: typeof GaleriRoute
  PrasastiRoute: typeof PrasastiRoute
  TentangRoute: typeof TentangRoute
  EnsiklopediaSlugRoute: typeof EnsiklopediaSlugRoute
  EnsiklopediaIndexRoute: typeof EnsiklopediaIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/galeri': {
      id: '/galeri'
      path: '/galeri'
      fullPath: '/galeri'
      preLoaderRoute: typeof GaleriRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/prasasti': {
      id: '/prasasti'
      path: '/prasasti'
      fullPath: '/prasasti'
      preLoaderRoute: typeof PrasastiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tentang': {
      id: '/tentang'
      path: '/tentang'
      fullPath: '/tentang'
      preLoaderRoute: typeof TentangRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ensiklopedia/': {
      id: '/ensiklopedia/'
      path: '/ensiklopedia'
      fullPath: '/ensiklopedia/'
      preLoaderRoute: typeof EnsiklopediaIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ensiklopedia/$slug': {
      id: '/ensiklopedia/$slug'
      path: '/ensiklopedia/$slug'
      fullPath: '/ensiklopedia/$slug'
      preLoaderRoute: typeof EnsiklopediaSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  GaleriRoute: GaleriRoute,
  PrasastiRoute: PrasastiRoute,
  TentangRoute: TentangRoute,
  EnsiklopediaSlugRoute: EnsiklopediaSlugRoute,
  EnsiklopediaIndexRoute: EnsiklopediaIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
